### ISSUE TITLE
setup.py fixes

### ISSUE THREAD

**Issue by goodmami** [xigt/igtdetect#1]
`distutils` is considered the "legacy" option for packaging, and even the standard docs [recommend](https://docs.python.org/3/distutils/index.html) `setuptools`. It seems `distutils` does not have the `install_requires` parameter (it has `requires`, I think). Anyway, I recommend switching to setuptools, which should be painless.

Also, Freki is listed on the install_requires parameter in setup.py, but Freki is not listed on PyPI, so it will not be automatically installed as a dependency. [Apparently](http://stackoverflow.com/a/3481388) you can specify alternative sources in a `dependency_links` parameter. Also see: http://python-packaging.readthedocs.io/en/latest/dependencies.html#packages-not-on-pypi

Lastly, I suggest using [semantic versioning](http://semver.org/) instead of two-digit versions. Summary from the semver website:

> Given a version number MAJOR.MINOR.PATCH, increment the:
> 
> 1. MAJOR version when you make incompatible API changes,
> 2. MINOR version when you add functionality in a backwards-compatible manner, and
> 3. PATCH version when you make backwards-compatible bug fixes.

**Comment by rgeorgi** [comment]
Resoluved by #eee751f62f626b19569d1242e4e8d8f5fd02dabf

**Comment by goodmami** [comment]
The Freki requirement isn't really fixed, I don't think. I haven't used `dependency_links`, but the resource I linked to made it sound like you keep `freki` on the `install_requires`, and ALSO include the link where to download it. The link should point to a tarball of the package (e.g. maybe `https://github.com/xigt/freki/tarball/master#egg=freki-0.1.0`).

**Comment by rgeorgi** [comment]
Thanks; added those corrections to latest commit.
